[features]
seeds = false
skip-lint = false
[programs.localnet]
concert_nft_tickets = "3oKZi6zmYzbRDuq8nAAGeL9m9TcwFPAiR2cfz4vjANum"

[programs.testnet]
concert_nft_tickets = "3oKZi6zmYzbRDuq8nAAGeL9m9TcwFPAiR2cfz4vjANum"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rianco13/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
