# Docker Compose file for Concert NFT Tickets
# Compatible with existing backend setup

services:
  concert-mongodb:
    image: mongo:latest
    container_name: concert-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - concert-network
    # No authentication - sesuai dengan setup existing Anda
    command: mongod --noauth

  concert-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: concert-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Environment variables PERSIS seperti .env Anda
      PORT: 5000
      MONGO_URI: mongodb://concert-mongodb:27017/concert_nft_tickets
      JWT_SECRET: d83jd72kDla9sjdK37dhLs95haKsn2j8dLak27d
      SOLANA_RPC_URL: https://api.testnet.solana.com
      PROGRAM_ID: 3oKZi6zmYzbRDuq8nAAGeL9m9TcwFPAiR2cfz4vjANum
      UPLOAD_PATH: ./public/uploads
      NODE_ENV: development
    volumes:
      # Mount source code untuk development
      - ./backend:/app
      - ./backend/public/uploads:/app/public/uploads
      # Exclude node_modules
      - /app/node_modules
    depends_on:
      - concert-mongodb
    networks:
      - concert-network
    # Gunakan npm start sesuai Dockerfile existing
    command: npm start

# Named volumes sesuai dengan setup existing
volumes:
  mongodb_data:
    driver: local
  # Volume untuk uploads sesuai dengan UPLOAD_PATH
  backend_uploads:
    driver: local

# Networks
networks:
  concert-network:
    driver: bridge
